version: 2
updates:
  # Backend Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: "auto"
    groups:
      typescript-types:
        patterns:
          - "@types/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      - dependency-type: "development"
        update-types: ["version-update:semver-major"]

  # Frontend React dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: "auto"
    groups:
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      mui-packages:
        patterns:
          - "@mui/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    ignore:
      - dependency-type: "development"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "infrastructure"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "develop"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"