# Elasticsearch Configuration
# Version: 7.x
# Environment: Production

#----------------------
# Cluster Settings
#----------------------
cluster:
  name: task-management-cluster
  initial_master_nodes: ["${NODE_NAME}"]
  routing:
    allocation:
      disk:
        threshold_enabled: true
        watermark:
          low: "85%"
          high: "90%"
      awareness:
        attributes: zone
      enable: all
  max_shards_per_node: 1000

discovery:
  seed_hosts: ["${DISCOVERY_SEEDS:elasticsearch}"]
  type: single-node

#----------------------
# Node Settings
#----------------------
node:
  name: "${NODE_NAME}"
  master: true
  data: true
  ingest: true
  ml: false
  attr:
    zone: "${ZONE:default}"
    box_type: hot
  processors: 4

#----------------------
# Path Settings
#----------------------
path:
  data: /usr/share/elasticsearch/data
  logs: /usr/share/elasticsearch/logs
  repo: ["/usr/share/elasticsearch/snapshots"]
  shared_data: /usr/share/elasticsearch/shared

#----------------------
# Network Settings
#----------------------
network.host: 0.0.0.0
http:
  port: 9200
  cors:
    enabled: true
    allow-origin: "*"
    allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
    allow-headers: X-Requested-With, Content-Type, Content-Length, Authorization
  max_content_length: "100mb"
  compression: true

transport:
  port: 9300
  tcp.compress: true

#----------------------
# Security Settings
#----------------------
xpack.security:
  enabled: true
  transport:
    ssl:
      enabled: true
      verification_mode: certificate
      keystore.path: elastic-certificates.p12
      truststore.path: elastic-certificates.p12
  audit:
    enabled: true
    logfile:
      events.include: ["access_denied", "authentication_failed", "connection_denied", "tampered_request"]
  authc:
    api_key.enabled: true
    token.enabled: true
    realms:
      native:
        native1:
          order: 0

#----------------------
# Memory Settings
#----------------------
bootstrap.memory_lock: true

indices:
  memory:
    index_buffer_size: "30%"
  queries.cache.size: "5%"
  fielddata:
    cache.size: "30%"
  breaker:
    total:
      use_real_memory: true
      limit: "70%"
    fielddata.limit: "40%"
    request.limit: "60%"

#----------------------
# Monitoring Settings
#----------------------
xpack.monitoring:
  enabled: true
  collection:
    enabled: true
    interval: "10s"
    cluster:
      stats.timeout: "10s"
    node:
      stats.timeout: "10s"
    indices:
      stats.timeout: "10s"
  elasticsearch.collection.enabled: true
  history.duration: "7d"